// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"post/ioc"
	"post/repository"
	"post/repository/dao"
	"post/service"
	"post/web"
)

// Injectors from wire.go:

func InitApp() *web.ArticleHandler {
	db := ioc.InitDB()
	articleDao := dao.NewGORMArticleDao(db)
	articleAuthorRepository := repository.NewArticleAuthorRepository(articleDao)
	articleReaderRepository := repository.NewArticleReaderRepository(articleDao)
	articleService := service.NewArticleService(articleAuthorRepository, articleReaderRepository)
	articleHandler := web.NewArticleHandler(articleService)
	return articleHandler
}
