// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"post/recommend/events"
	"post/recommend/grpc"
	"post/recommend/ioc"
	"post/recommend/service"
)

// Injectors from wire.go:

func InitApp() *App {
	gorseClient := ioc.InitGorse()
	recommendService := service.NewRecommendService(gorseClient)
	recommendServiceServer := grpc.NewRecommendServiceServer(recommendService)
	server := ioc.InitGrpcRecommendServer(recommendServiceServer)
	client := ioc.InitKafka()
	batchKafkaRecommendConsumer := events.NewKafkaRecommendConsumer(client)
	v := ioc.NewConsumers(batchKafkaRecommendConsumer)
	app := &App{
		server:    server,
		consumers: v,
	}
	return app
}
