// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/google/wire"
	"post/interactive/grpc"
	"post/interactive/repository"
	"post/interactive/repository/cache"
	"post/interactive/repository/dao"
	"post/interactive/service"
)

import (
	_ "embed"
)

// Injectors from wire.go:

func InitGRPCServer() *grpc.LikeServiceServer {
	gormDB := InitDB()
	articleLikeDao := dao.NewGORMArticleLikeDao(gormDB)
	cmdable := InitRedis()
	articleLikeCache := cache.NewRedisArticleLikeCache(cmdable)
	likeRepository := repository.NewLikeRepository(articleLikeDao, articleLikeCache)
	likeService := service.NewLikeService(likeRepository)
	likeServiceServer := grpc.NewLikeServiceServer(likeService)
	return likeServiceServer
}

// wire.go:

var thirdProvider = wire.NewSet(
	InitRedis, InitDB,
	InitLogger,
	InitKafka,
)
