// Code generated by MockGen. DO NOT EDIT.
// Source: ./service/like.go
//
// Generated by this command:
//
//	mockgen -source=./service/like.go -destination=./service/mock/like_mock.go --package=svcMocks
//

// Package svcMocks is a generated GoMock package.
package svcMocks

import (
	context "context"
	domain "post/interactive/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLikeService is a mock of LikeService interface.
type MockLikeService struct {
	ctrl     *gomock.Controller
	recorder *MockLikeServiceMockRecorder
}

// MockLikeServiceMockRecorder is the mock recorder for MockLikeService.
type MockLikeServiceMockRecorder struct {
	mock *MockLikeService
}

// NewMockLikeService creates a new mock instance.
func NewMockLikeService(ctrl *gomock.Controller) *MockLikeService {
	mock := &MockLikeService{ctrl: ctrl}
	mock.recorder = &MockLikeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLikeService) EXPECT() *MockLikeServiceMockRecorder {
	return m.recorder
}

// Collect mocks base method.
func (m *MockLikeService) Collect(ctx context.Context, objType string, objID, uid uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collect", ctx, objType, objID, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Collect indicates an expected call of Collect.
func (mr *MockLikeServiceMockRecorder) Collect(ctx, objType, objID, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collect", reflect.TypeOf((*MockLikeService)(nil).Collect), ctx, objType, objID, uid)
}

// GetListBatchOfLikes mocks base method.
func (m *MockLikeService) GetListBatchOfLikes(ctx context.Context, objType string, list *domain.List) ([]domain.Like, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListBatchOfLikes", ctx, objType, list)
	ret0, _ := ret[0].([]domain.Like)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListBatchOfLikes indicates an expected call of GetListBatchOfLikes.
func (mr *MockLikeServiceMockRecorder) GetListBatchOfLikes(ctx, objType, list any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListBatchOfLikes", reflect.TypeOf((*MockLikeService)(nil).GetListBatchOfLikes), ctx, objType, list)
}

// IncrReadCount mocks base method.
func (m *MockLikeService) IncrReadCount(ctx context.Context, objType string, objID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrReadCount", ctx, objType, objID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrReadCount indicates an expected call of IncrReadCount.
func (mr *MockLikeServiceMockRecorder) IncrReadCount(ctx, objType, objID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrReadCount", reflect.TypeOf((*MockLikeService)(nil).IncrReadCount), ctx, objType, objID)
}

// IncrReadCountMany mocks base method.
func (m *MockLikeService) IncrReadCountMany(ctx context.Context, objType string, objIDs []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrReadCountMany", ctx, objType, objIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrReadCountMany indicates an expected call of IncrReadCountMany.
func (mr *MockLikeServiceMockRecorder) IncrReadCountMany(ctx, objType, objIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrReadCountMany", reflect.TypeOf((*MockLikeService)(nil).IncrReadCountMany), ctx, objType, objIDs)
}

// Like mocks base method.
func (m *MockLikeService) Like(ctx context.Context, objType string, objID, uid uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Like", ctx, objType, objID, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Like indicates an expected call of Like.
func (mr *MockLikeServiceMockRecorder) Like(ctx, objType, objID, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Like", reflect.TypeOf((*MockLikeService)(nil).Like), ctx, objType, objID, uid)
}

// UnLike mocks base method.
func (m *MockLikeService) UnLike(ctx context.Context, objType string, objID, uid uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnLike", ctx, objType, objID, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnLike indicates an expected call of UnLike.
func (mr *MockLikeServiceMockRecorder) UnLike(ctx, objType, objID, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnLike", reflect.TypeOf((*MockLikeService)(nil).UnLike), ctx, objType, objID, uid)
}

// UpdateReadCountMany mocks base method.
func (m *MockLikeService) UpdateReadCountMany(ctx context.Context, objType string, hmap map[uint64]int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReadCountMany", ctx, objType, hmap)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateReadCountMany indicates an expected call of UpdateReadCountMany.
func (mr *MockLikeServiceMockRecorder) UpdateReadCountMany(ctx, objType, hmap any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReadCountMany", reflect.TypeOf((*MockLikeService)(nil).UpdateReadCountMany), ctx, objType, hmap)
}
